[package]
name = "redis-async"
version = "0.12.1"
authors = ["Ben Ashford <benashford@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "An asynchronous futures based Redis client for Rust using Tokio"
repository = "https://github.com/benashford/redis-async-rs"
keywords = ["redis", "tokio"]
edition = "2018"

[dependencies]
bytes_05 = { package = "bytes", version = "0.5", optional = true }
bytes_10 = { package = "bytes", version = "1.0", optional = true }
log = "^0.4.11"
futures-channel = "^0.3.7"
futures-sink = "^0.3.7"
futures-util = { version = "^0.3.7", features = ["sink"] }
tokio_02 = { package = "tokio", version = "0.2", features = ["rt-core", "net", "time"], optional = true}
tokio_10 = { package = "tokio", version = "1.0", features = ["rt", "net", "time"], optional = true }
tokio-util_03 = { package = "tokio-util", version = "0.3", features = ["codec"], optional = true }
tokio-util_06 = { package = "tokio-util", version = "0.6", features = ["codec"], optional = true }
tokio-util_07 = { package = "tokio-util", version = "0.7", features = ["codec"], optional = true }

[dev-dependencies]
env_logger = "^0.9"
futures = "^0.3.7"
tokio_02 = { package = "tokio", version = "0.2", features = ["full"] }
tokio_10 = { package = "tokio", version = "1.0", features = ["full"] }

[features]
default = ["tokio10"]

tokio02 = ["bytes_05", "tokio_02", "tokio-util_03"]
tokio10 = ["bytes_10", "tokio_10", "tokio-util_07"]